[package]
name = "derivs"
version = "0.1.0"
edition = "2021"
authors = ["Yagoub <ghaderi.yaghoub@gmail.com>"]
repository = "https://github.com/yghaderi/derivs.git"
license = "MIT"
license-file = "LICENSE.txt"
description = "مدل-سازیِ ابزارهایِ مشتقه"

[dependencies]
